USE ContosoRetailDW

--TOP 3 CLIENTES POR VENDAS
SELECT TOP 3
	customerKey AS C,
	SUM(SalesAmount) TotalVendas
FROM FactOnlineSales AS F
GROUP BY customerKey
ORDER BY TotalVendas DESC


--ANALISE POR REGIÃO (QTDE CLIENTES)
USE ContosoRetailDW
SELECT
	G.ContinentName,
	COUNT(DISTINCT(F.CustomerKey)) AS ContagemClientes
FROM FactOnlineSales AS F
INNER JOIN DimCustomer C ON C.CustomerKey = F.CustomerKey
INNER JOIN DimGeography G ON G.GeographyKey = C.GeographyKey
GROUP BY G.ContinentName

--TOP 5 VENDAS POR PRODUTO
SELECT TOP 5
OS.ProductKey AS ID,
P.ProductName AS Produto,
SUM(SalesAmount) AS TotalVendas
FROM FactOnlineSales OS
INNER JOIN DimProduct P ON P.ProductKey = OS.ProductKey
GROUP BY OS.ProductKey, P.ProductName
ORDER BY TotalVendas DESC

--VENDAS POR MES
SELECT
	DATEPART(YEAR, S.DateKey) AS ANO,
	DATEPART(MONTH, S.DateKey) AS MES,
	SUM(SalesAmount)
FROM FactOnlineSales S
GROUP BY DATEPART(YEAR, S.DateKey),	DATEPART(MONTH, S.DateKey);

--ANALISES YTD DAS VENDAS (VALOR ACUMULADO)

WITH TOTAL_VENDAS (ANO, MES, VENDAS) AS
(
	SELECT
		DATEPART(YEAR, S.DateKey) AS ANO,
		DATEPART(MONTH, S.DateKey) AS MES,
		SUM(SalesAmount) AS VENDAS
	FROM FactOnlineSales S
	GROUP BY DATEPART(YEAR, S.DateKey),	DATEPART(MONTH, S.DateKey)
)
SELECT
	ANO,
	MES,
	FORMAT(VENDAS, 'C0') AS 'VENDAS',
	FORMAT(SUM (VENDAS) OVER(PARTITION BY ANO ORDER BY MES), 'C0') AS VENDAS_YTD,
	FORMAT(SUM (VENDAS) OVER(PARTITION BY ANO), 'C0') AS VENTAL_TOTAL
FROM TOTAL_VENDAS
ORDER BY ANO, MES;

--ANALISES MoM
WITH TOTAL_VENDAS (ANO, MES, VENDAS) AS
(
	SELECT
		DATEPART(YEAR, S.DateKey) AS ANO,
		DATEPART(MONTH, S.DateKey) AS MES,
		SUM(SalesAmount) AS VENDAS
	FROM FactOnlineSales S
	GROUP BY DATEPART(YEAR, S.DateKey),	DATEPART(MONTH, S.DateKey)
)
SELECT
	ANO,
	MES,
	FORMAT (VENDAS, 'C0') AS 'VENDAS',
	FORMAT (LAG (VENDAS, 1, 0) OVER(ORDER BY ANO, MES), 'C0') AS MES_ANTERIOR
FROM TOTAL_VENDAS


